-- Drop all tables in the KBQDB database
--
SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `TKEYS`;
DROP TABLE IF EXISTS `ENTRIES`;
DROP TABLE IF EXISTS `LABELS`;
DROP TABLE IF EXISTS `NAMESPACES`;
DROP TABLE IF EXISTS `SOURCES`;

SET FOREIGN_KEY_CHECKS=1;
